# Generated by Django 5.2.1 on 2025-05-25 18:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('proposals', '0001_initial'),
        ('solicitations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='proposalfordonation',
            name='solicitor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='solicitors', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='proposalfordonation',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='proposalforsolicitation',
            name='potential_donor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='potential_donors', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='proposalforsolicitation',
            name='solicitation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proposals', to='solicitations.solicitation'),
        ),
        migrations.AddField(
            model_name='proposalforsolicitation',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
