# Generated by Django 5.2.1 on 2025-06-01 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='document',
        ),
        migrations.RemoveField(
            model_name='user',
            name='document_type',
        ),
        migrations.AddField(
            model_name='user',
            name='cnpj',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
    ]
