# Generated by Django 5.2.1 on 2025-06-04 16:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_baseentrycategory'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='baseentrycategory',
            name='description',
        ),
    ]
