# Generated by Django 5.2.1 on 2025-06-04 15:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_baseentrycategory'),
        ('donations', '0003_donation_local'),
    ]

    operations = [
        migrations.RenameField(
            model_name='donation',
            old_name='local',
            new_name='location',
        ),
        migrations.AddField(
            model_name='donation',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='core.baseentrycategory'),
        ),
    ]
